### ISSUE TITLE
CI and Vercel disagree on the same build, and only CI is a required check

### ISSUE THREAD

**Issue by richardkern** [ironsandsystems/richardkern-nz#176]
Found on #174, a routine Dependabot group bump.

`check` and `build` both **pass** on that commit. The Vercel build of the same commit **fails**:

```
Error: Turbopack build failed with 4 errors:
TypeError: __turbopack_context__.a is not a function

Import trace:
  geist/dist/geistmono_157ca88a.module.css
  ./src/app/(frontend)/layout.tsx
```

CI runs the identical `pnpm build`, on Node 24, on `ubuntu-latest`, installing from the same lockfile with `--frozen-lockfile`. So the same command in the same major runtime disagrees between the two environments, and the one that disagrees is the one that ships.

## Why it matters more than one bump

Branch protection on `main` requires `check` and `build`. It does **not** require the Vercel check. #174 is therefore mergeable as it stands, and merging it would break the production deploy — and since #170 collapsed the two-hop flow, a merge to `main` *is* the release, with no staging hop left to catch it.

This is the inverse of the concern recorded on #164. There the worry was a permanently red Vercel check training everyone to ignore checks. Here the required checks are green and the platform build is red, which is worse, because nothing prompts anyone to look.

## What needs deciding, in order

1. **Why do the two disagree?** Reproduce locally against #174's lockfile first. Candidates: Node minor version, since CI resolves `24` to whatever is current and Vercel pins its own; Turbopack behaviour differing by builder; or something Vercel injects into the build environment. **Do not add a required check before this is understood** — a required check that fails for environment reasons rather than code reasons is its own outage
2. **Should the Vercel check be required?** Probably yes once the above is understood, because it is the only check that exercises what actually deploys, including the migration against a real database branch
3. **Is anything else only caught by Vercel?** The sharp native-library fault during the migration was exactly this shape: a green build everywhere except the place it mattered

## Interim

#174 stays open and unmerged, with the reasoning on the PR. Anyone merging Dependabot PRs before this is resolved should read the Vercel check by hand rather than trusting the green tick, which is precisely the habit this card exists to stop relying on.

**Comment by richardkern** [comment]
Reproduced live today on #180, and the build log names a mechanism this card had not considered.

#180 is a **comments-and-deletions-only** change (removes `Dockerfile`/`.dockerignore`, rewords stale Coolify notes). It touches no dependency, no lockfile, and neither `globals.css` nor `postcss.config.js`. On commit `ee6092a`:

```
check   SUCCESS      <- required
build   SUCCESS      <- required
Vercel  FAILURE      <- not required
```

So the card's core worry is not hypothetical: #180 is mergeable right now and merging it would ship a broken production deploy.

## What the log shows

```
Restored build cache from previous deployment (35BjEtm5ZAsJDrobGcswf2Dsu4kn)
...
Error: Turbopack build failed with 1 error:
./src/app/(frontend)/globals.css
TypeError: __turbopack_context__.a is not a function
  at mod (postcss.config.js_.loader.mjs:11:31)
     [/vercel/path0/.next/build/chunks/[root-of-the-server]__0_4nzr9._.js:56:30]
```

The failure is **inside `.next/build/chunks/`** — restored artifacts, not source. `__turbopack_context__.a is not a function` is what mixing chunks from one Turbopack runtime with another produces.

That fits the divergence exactly: **CI builds cold on a fresh runner every time and cannot hit this. Vercel restores a `.next` cache between deployments and can.** Same command, same lockfile, same Node major, different starting state on disk.

## The obvious objection, checked

Cache restoration alone is not the discriminator — the builds that *passed* restored one too:

| Deployment | Commit | Restored cache from | Result |
|---|---|---|---|
| `hs9eux3fn` | `cf68f71` (#178) | `6ivj5woe…` | Compiled successfully |
| `1yu5vjhyd` | `609fa2f` (main) | `8fs5yYBz…` | Compiled successfully |
| `5t3r79ujk` | `ee6092a` (#180) | `35BjEtm5…` | **Turbopack error** |

So it is *which* cache gets restored, not whether one is. A first deployment on a new branch inherits a cache it did not produce, which is when the mismatch can appear.

Note also that the earlier #174 failure no longer implicates that bump: #174 **merged on 2026-08-13** and its dependency changes are on `main` building fine. Same content, different result, which rules out the content.

## The next move, and why I stopped short of it

The decisive test is one rebuild of `ee6092a` **without the build cache**. Green means confirmed.

`vercel redeploy` has no cache flag, so it needs either the dashboard's Redeploy dialog with *Use existing Build Cache* unchecked, or `VERCEL_FORCE_NO_BUILD_CACHE=1` on the project. The second is a project settings change, so it is Richard's call rather than mine.

If it confirms, this reframes the card's question 2. Requiring the Vercel check would turn a *cache* fault into a merge blocker on unrelated PRs, which is the "required check that fails for environment reasons" trap question 1 warns about. The fix would more likely be making the build cache-safe — the standard lever being `VERCEL_FORCE_NO_BUILD_CACHE` or a cache key that includes the Next/Turbopack version — with the required check coming after that.

Also worth noting from the same log, unrelated but visible:

```
Warning: Detected "engines": { "node": ">=24.0.0" } that will automatically upgrade
         when a new major Node.js Version is released.
```

The floating-Node concern in the pickup notes is real and worth pinning regardless, but it is **not** what caused this: the failure is in restored chunks, not a runtime difference.

**Comment by richardkern** [comment]
Correction to my comment above, after identifying what the restored caches actually were. **The "stale cache from an older Turbopack" story is wrong** — I inferred it from the error signature instead of checking, and checking breaks it.

The cache my failing build restored, `35BjEtm5…`, is deployment `1yu5vjhyd`: the **successful production build of `609fa2f` from 29 minutes earlier**, on the same Next 16.3.0. Not stale, not an older version, and not a failed build.

Resolving all three cache IDs gives a cleaner pattern:

| Build | Target | Restored cache from | Its target | Result |
|---|---|---|---|---|
| `hs9eux3fn` (#178, `cf68f71`) | Preview | `jfv2ymcep` (2d ago) | **Preview** | ✅ |
| `1yu5vjhyd` (main, `609fa2f`) | Production | `8ngu1s2ug` (2d ago) | **Production** | ✅ |
| `5t3r79ujk` (#180, `ee6092a`) | Preview | `1yu5vjhyd` (29m ago) | **Production** | ❌ |

Both successes restored a cache built for **the same target environment**. The one failure restored a **Production** cache into a **Preview** build.

## Why that would break, specifically

`next.config.ts` is not target-invariant. `VERCEL_ORIGINS` branches on `VERCEL_ENV === 'preview'`, and since #178 the `/admin` CSP header key branches on `VERCEL_ENV === 'production'`. So the evaluated config genuinely differs between targets, and the failure is in the chunk that evaluates config-adjacent code:

```
at mod (postcss.config.js_.loader.mjs:11:31)
   [/vercel/path0/.next/build/chunks/[root-of-the-server]__0_4nzr9._.js]
```

## Why a new branch is the risk case

A branch with no prior deployment has no cache of its own, so the fallback is the most recent deployment — which is whatever last shipped, often production. That predicts **the first build of any new branch is the exposed one**, and it fits both known failures: #174 was a fresh Dependabot branch, #180 is a fresh branch. #178's rebuild today had its own earlier preview cache to draw on and passed.

It also explains the thing that made #174 confusing — merging it to `main` worked. On `main` the build restores a *production* cache, so the mismatch never arises.

## What this changes

The discriminating test is unchanged: **redeploy `ee6092a` with the build cache off**. Green confirms it.

But the likely fix moves. If this is cross-target cache reuse, requiring the Vercel check (question 2) would make every new branch's first push a coin toss, which is exactly the trap question 1 warns about. The lever is to stop preview builds inheriting a production cache — `VERCEL_FORCE_NO_BUILD_CACHE=1`, or scoping the cache per target — and only then consider making the check required.

I have not run the confirming test: it needs the dashboard Redeploy toggle or a project settings change, both Richard's call.

**Comment by richardkern** [comment]
**Confirmed.** Richard redeployed `ee6092a` with the cache off, and the only variable that changed was the build cache.

```
Cloning ... (Branch: chore/151-remove-coolify-artifacts, Commit: ee6092a)
Skipping build cache, deployment was triggered without cache.
▲ Next.js 16.3.0 (Turbopack)
✓ Compiled successfully in 34.3s
Build Completed in /vercel/output [1m]
```

Same commit, same lockfile, same Node, same Next. The cached build errored at ~11s; the cold build compiles in 34.3s and ships. So the divergence in this card is **the build cache, not the code, not the dependencies, and not Node**.

Combined with the target mapping in my previous comment, the mechanism is: a branch with no cache of its own inherits the most recent deployment's, which is typically **Production**; `next.config.ts` evaluates differently by target; and the mixed chunks fail as `__turbopack_context__.a is not a function`. CI cannot hit this because it always builds cold.

## Where that leaves the card's three questions

1. **Why do the two disagree?** Answered. Vercel restores a build cache; CI never does.
2. **Should the Vercel check be required?** Not on its own, and not yet. As things stand it would fail on the first push of any new branch for reasons unrelated to that branch — the "required check that fails for environment reasons" this card explicitly warns against. Fix the cache scoping first, then require it.
3. **Is anything else only caught by Vercel?** Still open, and still worth its own look. The sharp native-library fault had this shape.

## Suggested next step, not taken

The durable fix is to stop preview builds inheriting a production cache. `VERCEL_FORCE_NO_BUILD_CACHE=1` is the blunt version and costs every build the full cold compile (35s vs 5s here, plus a 407 MB cache upload). A narrower option is worth checking first: whether Vercel can scope the cache per target, so previews only ever restore preview caches.

Worth noting the cost is asymmetric — an inherited-cache failure is a red check on an innocent PR, while a cold build is 30 seconds. If no per-target scoping exists, forcing no cache is the reasonable trade.

Deliberately **not** bundled in here: pinning the floating Node (`node-version: 24`, `engines: ">=24.0.0"`). Real, worth doing, and not causal — it should be its own change so it does not muddy this result.

**Comment by richardkern** [comment]
Checked whether per-target cache scoping exists before accepting the trade. **It does not, and the behaviour we hit is documented rather than a fault.**

[Vercel's build-cache docs](https://vercel.com/docs/deployments/troubleshoot-a-build#caching-process) list the cache key components:

> Personal Account or Team · Project · Framework Preset · Root Directory · **Node.js Version** · Package Manager · **Git branch**

The deployment target is **not** among them. The cache is scoped per *branch*, not per environment, and the fallback for a branch that has none is spelled out:

> "If you create a new Git branch in `MyCode` and make a commit to it, there is no cache for that specific branch. In this case, **the last production Deployment cache is used to create a preview deployment** and a new branch cache is created for subsequent commits to the new branch."

That is exactly what the deployment table in my earlier comment shows. So there is no setting to scope caches per target — cross-target inheritance on a branch's first build is the designed behaviour.

## Two consequences worth having on the record

**This recurs, and it is not self-healing.** From the same page: "failed builds will **not modify** the existing cache." A production cache that breaks preview builds stays put and keeps breaking the first build of every new branch until a *successful* production build replaces it.

**Only the first build of a branch is exposed.** Subsequent commits use the branch's own cache. That matches what we saw: #180's first build failed, and PR #178's rebuild — which had its own preview cache from two days earlier — passed.

## So the trade has to be accepted, in one of three forms

1. **`VERCEL_FORCE_NO_BUILD_CACHE=1` on the project.** Every build cold. Measured here: 34.3s compile versus about 5s cached, plus a 407 MB cache upload skipped. Costs roughly 30 seconds a deploy, permanently, on every build including production.
2. **Live with it and redeploy without cache when a first build fails.** Zero standing cost, but the failure looks like a code fault on an innocent PR and someone has to recognise it each time. That is the habit this card exists to stop relying on.
3. **Set the variable for Preview scope only.** Production keeps its cache and its fast builds; previews always build cold. This targets the actual failure — a *preview* inheriting a *production* cache — and leaves the case that never breaks alone.

**Option 3 looks right to me** and I have not applied it, since it is a project settings change. It costs about 30 seconds on preview builds only, which is the environment where the delay matters least.

## Either way, question 2 stays blocked on this

Making the Vercel check required before the cache is dealt with would turn a documented platform behaviour into a merge blocker on the first push of every new branch. That is the "required check that fails for environment reasons" trap named in question 1.

Separately, the floating-Node divergence from the same log is now fixed in #181 — not causal here, but note the docs confirm **Node.js Version is part of the cache key**, so a runtime change would invalidate caches. #181 does not, since `>=24.0.0` and `24.x` both resolve to the latest 24.x.

**Comment by richardkern** [comment]
One qualification, from watching #181 (the Node pin) go through as a second brand-new branch.

Its first preview build **restored a production cache and passed**:

```
Cloning ... (Branch: chore/pin-node-major, Commit: 72eb1bc)
Restored build cache from previous deployment (GDYPPCRXNUX4ccR7XhMv8YbMEHGV)
✓ Compiled successfully in 12.3s
```

`GDYPPCRX…` is the production deployment created when #180 merged, nine minutes earlier.

So the sequence holds together:

| Branch | Inherited production cache from | Result |
|---|---|---|
| #180 (`ee6092a`) | production build of `609fa2f` | ❌ |
| — | #180 merges, new production build `446ce23` | — |
| #181 (`72eb1bc`) | production build of `446ce23` | ✅ |

**But it means my earlier framing was too strong.** Inheriting a production cache is *necessary* for this failure, not *sufficient*. Most production caches restore into a preview build fine — this one did, minutes later. Something made the `609fa2f` cache specifically incompatible, and I have not identified what. Candidates I did not chase: that build's own cache ancestry, or that `609fa2f` is the #178 merge, which is the commit that introduced `VERCEL_ENV === 'production'` branching into the `/admin` CSP header in `next.config.ts`.

What is still solid, because it was tested rather than reasoned:

- The cache is the differentiator for #180. Cache-free rebuild of the identical commit passes; cached fails.
- New branches inherit the last production cache. Documented, and observed twice.
- CI cannot ever reproduce this, because it always builds cold.

What is **not** established is a rule for predicting which production caches are poisonous. So the risk is **intermittent**, not certain — which makes it worse to diagnose in the moment, not better, since the next occurrence will again look like a code fault on an unrelated PR.

That does not change the recommendation (preview-scoped `VERCEL_FORCE_NO_BUILD_CACHE=1`, roughly 30s on preview builds only), and it does not change the answer to question 2: the check should not become required while a documented platform behaviour can redden it unpredictably.

**Comment by richardkern** [comment]
**Applied.** `VERCEL_FORCE_NO_BUILD_CACHE=1` is set on **Preview scope only**, non-sensitive so it can be read back.

```
VERCEL_FORCE_NO_BUILD_CACHE   Non-sensitive   Preview   ← present
                                              Production ← absent (checked)
```

## Verified by the log line, not by the setting existing

The first attempt to verify was inconclusive and worth recording as a trap. A CLI `vercel redeploy` prints:

```
Skipping build cache, deployment was triggered without cache.
```

— which is the **same message a manual no-cache redeploy produces**, so it cannot distinguish the flag working from `redeploy`'s own behaviour. A git-triggered build prints a different line that names the variable:

```
Cloning ... (Branch: chore/pin-node-major, Commit: e6a2182)
VERCEL_FORCE_NO_BUILD_CACHE is set so skipping build cache step.
✓ Compiled successfully in 29.1s
```

That is the discriminating evidence: the same branch's *first* build restored a cache, and after the flag it skips one. Cost lands where predicted — 29-35s cold versus about 5s cached.

Production is deliberately untouched. It restores a *production* cache, which is the case never observed to break, and it keeps its fast builds.

## What this does and does not settle

It removes the failure mode from the environment where it was observed, so a preview build can no longer be reddened by a cache it did not create. It does **not** explain why the `609fa2f` production cache was incompatible in the first place — that remains unidentified, and the flag is mitigation rather than diagnosis.

Recorded in `AGENTS.md`'s env table (a project setting invisible in the repo is a setting nobody reviews, the same reasoning already applied to `vercel.json`), including the redeploy trap above.

## Question 2 is now unblocked, with a caveat

Requiring the Vercel check is defensible once this has some mileage: previews no longer inherit foreign caches, so the environmental red-check risk this card warned about is gone from that path. Worth leaving a few days of real PRs before flipping it, since the underlying incompatibility is still unexplained and production still uses a cache.

Question 3 — whether anything else is caught only by Vercel — is still open and still worth its own pass.

**Comment by richardkern** [comment]
**Closing this** (2026-08-16), with one item split out rather than closed inside it.

## What was settled

The cause is understood: **Vercel's build cache key does not include the deployment target**, so a branch with no cache of its own restores the last *production* deployment's. The mitigation is applied and verified by the discriminating log line rather than by the setting existing — `VERCEL_FORCE_NO_BUILD_CACHE=1` at **Preview scope only**, so previews always build cold at about 30s against 5s, and production keeps its cache and the case never observed to break.

## What is not settled, and is being retired as a known unknown rather than tracked

Inheriting a production cache turned out to be **necessary but not sufficient**: the very next branch restored a production cache minutes later and built fine. What made `609fa2f`'s cache specifically incompatible was never identified, and the leading unchased candidate is that it is the #178 merge, which introduced `VERCEL_ENV === 'production'` branching.

That question is now **unreachable by design**: previews never restore a cache, so it cannot recur where it was observed, and there is no way to investigate it without removing the mitigation to reproduce a fault we have already fixed. Left recorded here rather than as an open card, because a card nobody can action is worse than a note someone can find.

## What moved to its own card

**#190** — nothing required on `main` exercises what actually deploys. That was point 2 of this card, and it is a different question: this card was one build failing, that one is the gap that made the failure dangerous, and the gap survives the fix. #176's own second example, sharp's native library missing from the function bundle, is evidence it will recur in a new shape. The environment-reasons objection that blocked requiring the check is now gone, which is exactly why it deserves a live card rather than a closing paragraph.

## Housekeeping

`keep/176-vercel-ci-divergence` is deleted. It held one commit, `6b2a378`, a copy of #174's bump kept as the repro, and it could no longer reproduce anything because the mitigation makes previews build cold. The commit is preserved as the tag **`repro/176`**, which pins it permanently while creating no preview deployment and therefore no Neon branch. That branch had been holding one of ten Neon branch slots since 2026-08-13.
